### ISSUE TITLE
[rawx] ununderstandable errors when we can't add extended attribute to a rawx directory

### ISSUE THREAD

**Issue by sebastienlapierre** [open-io/oio-sds#1027]
openio-sds version: 3.2.3

Case: Create a partition nearly full and try to deploy a rawx on it.

Problem: The rawx service failed to start because it can't set extended attribut on its directory, but the error is not understandable.
```[Mon Jun 05 08:53:44.404583 2017] [core:error] [pid 30980:tid 140036709234560] (EAI 2)Name or service not known: AH00549: Failed to resolve server name for 10.0.0.89 (check DNS) -- or specify an explicit ServerName```

Is it possible to have a sensible error ?

**Comment by jfsmig** [comment]
When I deploy a rawx on a full partition, I get an understandable error message that describes what happens

`[Wed Jul 19 17:28:40.320423 2017] [core:error] [pid 15366:tid 140185049968128] Failed to grab the docroot ownership: XATTR set error: No space left on device`

**Comment by jfsmig** [comment]
The message you pasted seems to mention an unresolvable ServerName. Are you sure there is no typo in the configuration, around the `ServerName` value?

When I try to reproduce, specifying a dummy `ServerName` doesn't cause a startup error (but i get something similar when the VirtualHost is wrong). Can you, please, paste a rawx configuration?

**Comment by jfsmig** [comment]
@sebastienlapierre I reproduce this when there is an explicit IP address that is not present on any interface of the current host. There is no relation with a full partition.

The message is generated by the httpd core. To file a bugreport, please follow the instructions at http://httpd.apache.org/bug_report.html.
