### ISSUE TITLE
Detect wrong config file entries

### ISSUE THREAD

**Issue by vincent-legoll** [open-io/oio-sds#1030]
A warning should be logged in case a wrong config entry is present in a config file.

This is invaluable for a newcomer to help him debug his configuration-related problems, and allow to quickly rule out a whole class of config errors.

This will also catch config entry migrations (moved to a new file, renamed)

**Comment by fvennetier** [comment]
This is partially addressed by #1038.

**Comment by jfsmig** [comment]
We could log warnings when obsolete keys are encountered. This is what has been done with #1038, in the context of the configuration parsing for the conscience. And this is the direction we should follow for the subsequent config. changes.

But some files do not have strong formats, with a small set of mandatory prefixes. And even "left open" for several applications (e.g. the /etc/oio/sds.conf files). And it would require a lot of "not immediately required work despite an appreciable result".
