### ISSUE TITLE
Container creation returns false on SDS 3.3.0

### ISSUE THREAD

**Issue by vdombrovski** [open-io/oio-sds#1037]
Using typical install for OpenIO 3.3.0 on CentOS7 (installed via puppet), when I create a container, I get created=false, yet the container still gets created

```sh
[root@test01 centos]# openio container create box2
+------+---------+
| Name | Created |
+------+---------+
| box2 | False   |
+------+---------+
[root@test01 centos]# openio container list
+------+-------+-------+
| Name | Bytes | Count |
+------+-------+-------+
| box  |     0 |     0 |
| box2 |     0 |     0 |
+------+-------+-------+
```

Package info:
```
$ rpm -qa | grep openio-sds
openio-sds-mod-httpd-3.3.0-1.el7.oio.x86_64
openio-sds-logrotate-1.6-1.el7.oio.noarch
openio-sds-common-3.3.0-1.el7.oio.x86_64
openio-sds-server-3.3.0-1.el7.oio.x86_64
puppet-openio-sds-1.1.75-1.el7.oio.noarch
openio-sds-rsyslog-1.2-1.el7.oio.noarch
```

**Comment by aneutron** [comment]
Can confirm. Using the 4.x version at the time of writing, the container based-instance returns false even though it creates the container, and the normal cluster installed with puppet returns true.

_Note: Also with the container, some commands like `openio account show` fail while raising no account server, while `openio account create` create the account._

**Comment by fvennetier** [comment]
Hello. There were some inconsistencies in the 3.x versions, but this is fixed in 4.x.
You should get `true` when the container is actually created, `false` when it existed already, and an error if the creation has failed.
