### ISSUE TITLE
oio_sds_init() api does not allow proxy initialization from non conf-file sources

### ISSUE THREAD

**Issue by linuxmonk** [open-io/oio-sds#1040]
The current implementation of ```oio_sds_init(struct oio_sds_s **out, const char *ns)``` always tries to read the proxy URL from sds.conf. This mandates the client side to maintain this configuration file. I am writing an application where I prefer all my configuration elements be present in my application configuration file. 

Can you please add the ability to initialize the sds structure without certain arguments (such as proxy IP) and then add extra API methods to set the proxy IP and so on.

**Comment by jfsmig** [comment]
Hi, @linuxmonk.

Sorry for replying so late. You are right, there is no clean way to force a proxy for the meta-data-related operations.

Though there is a way to do, if you are still interested in a workaround. The C SDK internally uses a set of functions sharing a global cache. By default, no cache is configured and the configuration is read each time a `struct oio_sds_s` is instanciated.

You could activate an empty cache with the call `oio_cfg_set_handle(oio_cfg_cache_create());`, when you initiate your process. But the trick, here, consists in preloading the cache with the entries you will target, with the help of a temporary file with a short lifetime:

```c
static void _preconfigure(const char *ns, const char *proxy) {
    const char *base = g_getenv("TMPDIR") ?: "/tmp";

    GString *cfg = g_string_new("");
    g_string_printf(cfg, "[%s]\nproxy=%s\n", ns, proxy);

    GString *path = g_string_new("");
    g_string_printf(path, "%s/plop-XXXXXX", base);

    int fd = g_mkstemp_full(path->str, O_RDWR, 0600);
    assert(fd >= 0);
    int written = write(fd, cfg->str, cfg->len);
    g_assert_cmpint(written, ==, cfg->len);

    oio_cfg_set_handle(oio_cfg_cache_create_fragment(path->str));

    unlink(path->str);
    close(fd), fd = -1;

    g_string_free(cfg, TRUE);
    g_string_free(path, TRUE);
}
```

Then if you want to flush the cache, simply call `oio_cfg_set_handle(NULL);`.

This is glib2-flavored, one could make it much shorter.
Also don't do this too more than once per process without flushing the cache, you would leak memory.

I hope it helps, while we make this simpler.
