### ISSUE TITLE
OpenIO with remote S3 storage

### ISSUE THREAD

**Issue by at88mph** [open-io/oio-sds#1057]
Hello,

Our use case is to have a federated layer to connect to existing remote storage sites. We have satellite S3, POSIX, and Swift storage sites, but need a federation layer to manage GET and PUTs to those sites.

Does anyone have experience with this?

Thanks!

**Comment by jfsmig** [comment]
Hello @at88mph.

Aggregating several object storages, or even translating their various flavors, this speaks to us. But this is currently not our job.
