### ISSUE TITLE
Test grid_client.h : wrong error code on container not found

### ISSUE THREAD

**Issue by Reaskel** [open-io/oio-sds#106]
A lot of grid_client functions which use to work perfectly now return "error 406 : code not managed" when called with a wrong reference argument, instead of returning "error 431 : container not found" like before.

Here are some of the concerned functions :
> Has_reference
Link_service_to_reference
Unlink_reference_service
List_reference_service
Poll_service
Force_service
Configure_service

**Comment by jfsmig** [comment]
The client has been removed
