### ISSUE TITLE
Test rawx-apache2 : no error raised when a content is put without all its headers

### ISSUE THREAD

**Issue by Reaskel** [open-io/oio-sds#108]
When sending a data put request to a rawx while forgetting at least one header (e.g. "chunk-id", "content_path" or "content_containerid"), the request is treated without raising any error. So data can be saved with incomplete location informations.

Could it be possible to implement a procedure to check the presence of every content header when sent via put requests ?

**Comment by jfsmig** [comment]
A few headers are really mandatory and, you are right, no error is raised when we lack them.

Fix pending ...
