### ISSUE TITLE
Concurrent restore op with same range offsets race condition

### ISSUE THREAD

**Issue by aneutron** [open-io/oio-sds#1138]
When restoring containers, if by chance two requests are issued to restore the same containers, with the same range offsets, there is no management of the said edge case.

A suggestion that could solve the problem is to adapt a rate-limiting solution to the problem, for example the [Redis Cell](https://github.com/brandur/redis-cell) module that provides in-redis ticket management, which makes it easier to integrate into the backup app that already uses redis to store data.

**Comment by murlock** [comment]
Closed by PR #1157
