### ISSUE TITLE
Interrupted restores can potentially break the container

### ISSUE THREAD

**Issue by aneutron** [open-io/oio-sds#1146]
When restoring a container, if for example we initialize the request with a content length of 512+512 bytes, but interrupt the request at the 512+511 byte, the first 512 bytes will be written to rawx, but the redis key will not be updated accordingly, all while raising an [UnprocessableEntity](https://github.com/open-io/oio-sds/blob/4.0.x/oio/container/backup.py#L772) exception.

As such, on the next retry to continue the restore operation, at least one object will be corrupted. _(According to @murlock)_.

To avoid having to restart the whole restore process, the redis key could be saved up to the last block that was written to RAWX.

**Comment by murlock** [comment]
Closed by PR #1157
