### ISSUE TITLE
How can i access WebUI?

### ISSUE THREAD

**Issue by qwe123wsx** [open-io/oio-sds#1270]
I have installed puppet master in 3 node, how can i access OpenIO's WebUI? I tried opening port 6000-6010 from browser but no response..

What should i install?

**Comment by jfsmig** [comment]
Hi, @qwe123wsx!

Thanks for testing us! The WebUI you target is not part of the open source toolkit of OpenIO. Feel free to require deeper information at info@openio.io, we are eager to consider your use case!
