### ISSUE TITLE
openio container create kstorage4 raise "Backend error: META0 partially missing (HTTP 500) (STATUS 500)"

### ISSUE THREAD

**Issue by sebheitzmann** [open-io/oio-sds#1349]
I've just installed a new cluster and i'm unable to create a new container.

I don't know how to diagnose this problem. 
I'm new to openio but very enthousiast ;-)

**Comment by sebheitzmann** [comment]
everything seems to be ok 

> root@s001:~# gridinit_cmd status
KEY                       STATUS      PID GROUP
OPENIO-account-0          UP         3376 OPENIO,account,account-0
OPENIO-beanstalkd-0       UP         3378 OPENIO,beanstalkd,beanstalkd-0
OPENIO-conscience-0       UP         3369 OPENIO,conscience,conscience-0
OPENIO-conscienceagent-0  UP         3383 OPENIO,conscienceagent,conscienceagent-0
OPENIO-meta0-0            UP         3370 OPENIO,meta0,meta0-0
OPENIO-meta1-0            UP         3374 OPENIO,meta1,meta1-0
OPENIO-meta2-0            UP         3373 OPENIO,meta2,meta2-0
OPENIO-oio-blob-indexer-0 UP         3379 OPENIO,oio-blob-indexer,oio-blob-indexer-0
OPENIO-oio-event-agent-0  UP         3372 OPENIO,oio-event-agent,oio-event-agent-0
OPENIO-oioproxy-0         UP         3375 OPENIO,oioproxy,oioproxy-0
OPENIO-rawx-0             UP         3371 OPENIO,rawx,rawx-0
OPENIO-rdir-0             UP         3381 OPENIO,rdir,rdir-0
OPENIO-redis-0            UP         3382 OPENIO,redis,redis-0
OPENIO-redissentinel-0    UP         3380 OPENIO,redissentinel,redissentinel-0
OPENIO-zookeeper-0        UP         3377 OPENIO,zookeeper,zookeeper-0

> root@s001:~# openio --oio-ns OPENIO cluster list
+---------+--------------------+---------------------------------+----------+-------+------+-------+
| Type    | Id                 | Volume                          | Location | Slots | Up   | Score |
+---------+--------------------+---------------------------------+----------+-------+------+-------+
| rdir    | xx.90.60:6010  | /var/lib/oio/sds/OPENIO/rdir-0  | s001     | n/a   | True |     0 |
| rdir    | xx.90.90:6010  | /var/lib/oio/sds/OPENIO/rdir-0  | s002     | n/a   | True |    99 |
| rdir    | xx.90.109:6010 | /var/lib/oio/sds/OPENIO/rdir-0  | s003     | n/a   | True |    99 |
| account | xx.90.60:6009  | n/a                             | s001     | n/a   | True |     0 |
| account | xx.90.90:6009  | n/a                             | s002     | n/a   | True |    98 |
| account | xx.90.109:6009 | n/a                             | s003     | n/a   | True |    97 |
| rawx    | xx.90.60:6004  | /var/lib/oio/sds/OPENIO/rawx-0  | s001     | n/a   | True |     0 |
| rawx    | xx.90.109:6004 | /var/lib/oio/sds/OPENIO/rawx-0  | s003     | n/a   | True |   100 |
| rawx    | xx.90.90:6004  | /var/lib/oio/sds/OPENIO/rawx-0  | s002     | n/a   | True |   100 |
| meta2   | xx.90.60:6003  | /var/lib/oio/sds/OPENIO/meta2-0 | s001     | n/a   | True |     0 |
| meta2   | xx.90.90:6003  | /var/lib/oio/sds/OPENIO/meta2-0 | s002     | n/a   | True |   100 |
| meta2   | xx.90.109:6003 | /var/lib/oio/sds/OPENIO/meta2-0 | s003     | n/a   | True |   100 |
| meta1   | xx.90.60:6002  | /var/lib/oio/sds/OPENIO/meta1-0 | s001     | n/a   | True |     0 |
| meta1   | xx.90.90:6002  | /var/lib/oio/sds/OPENIO/meta1-0 | s002     | n/a   | True |    99 |
| meta1   | xx.90.109:6002 | /var/lib/oio/sds/OPENIO/meta1-0 | s003     | n/a   | True |   100 |
| meta0   | xx.90.60:6001  | /var/lib/oio/sds/OPENIO/meta0-0 | s001     | n/a   | True |     0 |
| meta0   | xx.90.109:6001 | /var/lib/oio/sds/OPENIO/meta0-0 | s003     | n/a   | True |    98 |
| meta0   | xx.90.90:6001  | /var/lib/oio/sds/OPENIO/meta0-0 | s002     | n/a   | True |    99 |
+---------+--------------------+---------------------------------+----------+-------+------+-------+

**Comment by sebheitzmann** [comment]
I have a 0 score on my first node. Is it a proble ?

**Comment by vdombrovski** [comment]
Hello @sebheitzmann. Looks like your scores are locked on the first node, please run `openio cluster unlockall --oio-ns OPENIO` on any of your 3 nodes, wait a few seconds, then do `openio --oio-ns OPENIO cluster list` once again. Check whether your scores get unlocked, and if so, try to create your container once again.

**Comment by sebheitzmann** [comment]
> | meta0   | x.90.60:6001  | /var/lib/oio/sds/OPENIO/meta0-0 | s001     | n/a   | True |    93 |
| meta0   | x.90.109:6001 | /var/lib/oio/sds/OPENIO/meta0-0 | s003     | n/a   | True |    99 |
| meta0   | x.90.90:6001  | /var/lib/oio/sds/OPENIO/meta0-0 | s002     | n/a   | True |    97

the score is know ok but it still don't work

root@s001:~# openio container create kstorage4 --oio-account kiwi --oio-ns OPENIO
Directory error: Backend error: META0 partially missing (HTTP 500) (STATUS 500)

**Comment by vdombrovski** [comment]
Did you do `openio --oio-ns=OPENIO directory bootstrap --replicas 3` when bootstrapping? Did it succeed? Did you restart meta0/meta1 services **on all 3 nodes** afterwards using `gridinit_cmd restart @meta0 @meta1`?

**Comment by sebheitzmann** [comment]
It works. Thank you very much.

I think that i've done that but maybe not. Sorry.
