### ISSUE TITLE
Proxy/meta2 : meta2 process aborted on deleting content properties 

### ISSUE THREAD

**Issue by Reaskel** [open-io/oio-sds#139]
After having initialized a meta2 content with random properties and asked the proxy for deleting one of these properties, the meta2 process crashes with a SIGABRT signal. Meanwhile, the proxy surprisingly returns a 204 answer on the deletion request.

Here is the trace : 
> Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7f0006855700 (LWP 17900)]
0x00007f00087775d7 in raise () from /lib64/libc.so.6
(gdb) bt
0  0x00007f00087775d7 in raise () from /lib64/libc.so.6
1  0x00007f0008778cc8 in abort () from /lib64/libc.so.6
2  0x00007f00087b7e07 in __libc_message () from /lib64/libc.so.6
3  0x00007f00087bf1fd in _int_free () from /lib64/libc.so.6
4  0x00007f000b23658f in g_free () from /lib64/libglib-2.0.so.0
5  0x00007f000bd75200 in g_free0 (p=0x7effe0009940)
    at /home/blextrait/public_git/github.com/oio-sds/metautils/lib/utils_tools.c:206
6  0x000000000040b43f in _input_data_clean (input_data=0x7effe00347a0)
    at /home/blextrait/public_git/github.com/oio-sds/meta2v2/meta2_filter_context.c:66
7  0x000000000040b580 in meta2_filter_ctx_clean (ctx=0x7effe0021e00)
    at /home/blextrait/public_git/github.com/oio-sds/meta2v2/meta2_filter_context.c:117
8  0x0000000000405818 in meta2_dispatch_all (reply=0x7f0006854b50, gdata=0x1ada880, 
    hdata=0x60fae0 <M2V2_PROPDEL_FILTERS>)
    at /home/blextrait/public_git/github.com/oio-sds/meta2v2/meta2_gridd_dispatcher.c:82
9  0x00007f000b92b4aa in _client_call_handler ()
    at /home/blextrait/public_git/github.com/oio-sds/server/transport_gridd.c:730
10 0x00007f000b92be20 in _client_manage_l4v (client=0x7efff4001a00, gba=0x7effe0020890)
    at /home/blextrait/public_git/github.com/oio-sds/server/transport_gridd.c:810
11 0x00007f000b92ac55 in transport_gridd_notify_input (clt=0x7efff4001a00)
    at /home/blextrait/public_git/github.com/oio-sds/server/transport_gridd.c:508
12 0x00007f000b9290c8 in _notify ()
    at /home/blextrait/public_git/github.com/oio-sds/server/network_server.c:1443
13 0x00007f000b929209 in _client_manage_input ()
    at /home/blextrait/public_git/github.com/oio-sds/server/network_server.c:1467
14 0x00007f000b9293d0 in _client_manage_event (clt=0x7efff4001a00, events=1)
    at /home/blextrait/public_git/github.com/oio-sds/server/network_server.c:1537
15 0x00007f000b92800f in _work_on_client (srv=0x1a76280, clt=0x7efff4001a00)
    at /home/blextrait/public_git/github.com/oio-sds/server/network_server.c:1043
16 0x00007f000b928253 in _thread_cb_worker (td=0x1a76280)
    at /home/blextrait/public_git/github.com/oio-sds/server/network_server.c:1092
17 0x00007f000b2566b5 in g_thread_proxy () from /lib64/libglib-2.0.so.0
18 0x00007f000852ddf5 in start_thread () from /lib64/libpthread.so.0
19 0x00007f00088381ad in clone () from /lib64/libc.so.6

**Comment by jfsmig** [comment]
Fixed in #148 and #147.

**Comment by jkasarherou** [comment]
The bug is not fixed yet

**Comment by jfsmig** [comment]
Can you please provide a minimal script to reproduce it ?

**Comment by jkasarherou** [comment]
#212
