### ISSUE TITLE
Proxy/meta2 : too many answers on get container with a max parameter

### ISSUE THREAD

**Issue by Reaskel** [open-io/oio-sds#152]
When doing a get request on containers with the 'max' parameters set to N, the response contains N+1 contents.

**Comment by jkasarherou** [comment]
Can you provide an example ?

**Comment by Reaskel** [comment]
Through my python tests, I put 5 contents on a container. Then I did a get request on the container with the following parameters : 
> params={'max': 3}

I extracted the 'objects' field from the json answer and obtained 4 contents

**Comment by jfsmig** [comment]
Fixed in #171
