### ISSUE TITLE
Proxy/meta2 : error code 500 on set container property with an invalid key

### ISSUE THREAD

**Issue by Reaskel** [open-io/oio-sds#153]
When trying to set a container property with an invalid key ( = not included in the authorized property key parameters ), the http error code is 500 instead of 400 even if the answer's content is correct.

**Comment by jfsmig** [comment]
Please give sample requests to reproduce the problem (url + body)

**Comment by Reaskel** [comment]
First, create a reference, link it and create the container : 

> self.session.post("http://$IP:PORT/v3.0/$NS/reference/create",
                                 params={"acct":"acctest","ref":"reftest"})
> self.session.post("http://$IP:PORT/v3.0/$NS/reference/link",
                                 params={"type":"meta2","acct":"acctest","ref":"reftest"})
> self.session.post("http://$IP:PORT/v3.0/$NS/container/create",
                                 params={"acct":"acctest","ref":"reftest"})

Then try to set a property with a non authorized key : 

>self.session.post("http://$IP:PORT/v3.0/$NS/container/set_properties",
                                 params={"acct":"acctest","ref":"reftest"},
                                 data=json.dumps({'error': 'error_property'}))

The http answer code is 500, the json content answer is {"status":400,"message":"HOOK error: Request error: Invalid property name"}
