### ISSUE TITLE
proxy: refactor request/response format

### ISSUE THREAD

**Issue by jkasarherou** [open-io/oio-sds#184]
Actually, the proxy uses a mix of headers, query parameters, and field JSON encoded in the request body. We should stop using headers at all (we have full control on the request/response body format) and  use JSON.
Example: To set properties on a container creation:
instead of sending parameters as headers (which is confusing for parameters case sensitivity), we should simply use the JSON encoded body.

**Comment by jfsmig** [comment]
:up:

**Comment by jkasarherou** [comment]
let's do this

**Comment by jfsmig** [comment]
A lot of improvements have been done here, in a round ended with #686 .
