### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by pierlauro** [open-io/oio-sds#1857]
Hello,
is there any plan to update OIO tools in order to be executed with a Python 3 interpreter? The code base is still in Python 2 (old print syntax, use of xrand, ...) and in few months the old interpreter [will not be maintained anymore](https://www.pythonclock.org).

**Comment by fvennetier** [comment]
Hello. Most of the code is now compatible with Python 3. Starting from version 6.0.0 (the current master branch), the CI will run tests with both Python 2 and Python 3.
