### ISSUE TITLE
Load-Balancing: a necessary review to reduce its complexity

### ISSUE THREAD

**Issue by jfsmig** [open-io/oio-sds#190]
Currently, the load-balancing has several drawbacks:
* It plays with `service_info_s`, and it is one of the last parts of the code to do so. `service_info_s` is the structure that notoriously prevent us to use logical ID for services instead of network addresses.
* The current complexity trade-off between time and space clearly targets space. This is a bad idea since one service item is rather small.
* Under certain circumstances, the output is not guaranteed. This can happen if the election criterions target too few services in a huge set of not-targetted services with the same type.
* The implementation is rather hard to read, and harder to extend.
* The API is hard to use.
* The current implementation of the locations is to fuzzy to be really efficient with decent compute times.

I propose to reorganize this API to make it easy to use (simple API), with guaranteed output and response time (better internal structures, stronger locations):
* Build pools of services, gathering all the services pollable in the same call. In other words: compatble  types / tags / class
* In a pool, store the services in per-location-buckets: into a bucket, all the services are considered too close to be polled in the same API call.
* Poll services from a pool, with only parameters the number of services targeted and locations constraints.

**Comment by jfsmig** [comment]
With such a configuration for the `namespace_info_s`:
```json
{
  "ns" : "MYNS",
  "chunksize" : 1234567,
  "options" : {},
  "lb.pools" : {
    "meta2-fast-europe" : {"zone":"EU", "class":"SSD", "type":"meta2"},
    "meta2-slow-europe" : {"zone":"EU", "class":"SATA", "type":"meta2"},
    "meta2-slow-america" : {"zone":"US", "class":"SATA", "type":"meta2"},
    "sqlx-fast-europe" : {"zone":"EU", "class":"SSD", "type":"sqlx"},
    "sqlx-slow-europe" : {"zone":"EU", "class":"SATA", "type":"sqlx"},
    "sqlx-slow-america" : {"zone":"US", "class":"SATA", "type":"sqlx"},
    "rawx-fast-europe" : {"zone":"EU", "class":"SSD", "type":"rawx"},
    "rawx-slow-europe" : {"zone":"EU", "class":"SATA", "type":"rawx"},
    "rawx-slow-america" : {"zone":"US", "class":"SATA", "type":"rawx"}
  },
  "services_policy": {
    "meta2" : [ "1,meta2-fast-europe", "2,rawx-slow-europe,rawx-slow-america" ],
    "sqlx" : [ "1,sqlx-fast-europe", "2,sqlx-slow-europe,sqlx-slow-america" ]
  },
  "storage_policy": {
    "DUP-5" : {
      "type" : "replication",
      "data" : [
        "1,rawx-fast-europe,rawx-slow-europe",
        "2,rawx-slow-europe,rawx-slow-america",
        "2,rawx-slow-america,rawx-slow-europe",
      ]
    },
    "LIB-5-2" : {
      "type" : "jerasure",
      "data" : [
        "1,rawx-fast-europe,rawx-slow-europe",
        "2,rawx-slow-europe,rawx-slow-america",
        "2,rawx-slow-america,rawx-slow-europe"
      ],
      "parity" : [
        "1,rawx-slow-europe,rawx-slow-america",
        "1,rawx-slow-america,rawx-slow-europe"
      ]
   }
}
```

It becomes easy to provide a (nearly single) API to poll the right number of services from a sequence of target descriptions.

**Comment by jfsmig** [comment]
A LB review is considered as not a priority.

**Comment by fvennetier** [comment]
The current implementation puts each service in a generic pool named after the type of the service (e.g. "rawx") and another one named after the type and storage class (e.g. "rawx-ssd"). This is useless since we have no way to specified the storage class of a service. So, how would you like to specify the appartenance of a service to one or several pools ?
