### ISSUE TITLE
meta0-init not initializing every meta0 correctly

### ISSUE THREAD

**Issue by racciari** [open-io/oio-sds#193]
During a meta0-init, even if the meta0s are registered into the conscience, some of them might not be correctly initialized.
This problem arrived on AWS EC2 instances and is reproductible.

Is there a way to re-init a meta0 that wasn't initialized in the middle of other initialized meta0s ?

**Comment by jfsmig** [comment]
There is not yet the "reset" command. but this is easy to implement and a handy workaround.

What did cause the initiation failure ? A replication error ? An unexpected symptom ?

**Comment by racciari** [comment]
I did not investigate further for now, I'll re-try it early next week.

**Comment by jfsmig** [comment]
Hint : try to send a "refresh" command to the meta0 that seem unintialized. I am interested in their status after the operation. Thx!

**Comment by jfsmig** [comment]
:up:

**Comment by jfsmig** [comment]
Could you reproduce this bug?

**Comment by racciari** [comment]
Yes, it's very easy, just use meta0-init with 3 replicas.

**Comment by sebastienlapierre** [comment]
A contribution to the building:
At first start, sometimes, meta0 doesn't want to start if the zookeeper is not bootstrapped.

Log meta0:
> 2016-03-14T13:38:36.272217+00:00 bench-node3 OIO,OPENIO,meta0,0: info  3306 361F log INF oio.sqlite zk_main_watch(0x11ec800,-1,3,,0x11f3250)
2016-03-14T13:38:36.276710+00:00 bench-node3 OIO,OPENIO,meta0,0: warning  3306 311D log WRN oio.m0v2 Zk manager init failed : (0) zk base node [/hc/ns/OPENIO/srv/meta0] doesn't exist, zk code [-101]
2016-03-14T13:38:36.276780+00:00 bench-node3 OIO,OPENIO,meta0,0: warning  3306 311D log WRN oio.utils User init error

**Comment by sebastienlapierre** [comment]
The only way to start meta0 correctly is to restart meta0 after having bootstrapped the zookeeper.
Then you can init the meta0 safely.

**Comment by fvennetier** [comment]
In PR #561 I changed the way meta0 replicates on peers so the whole database is copied instead of the delta. This is way faster (7s to 1.2s on my environment).
