### ISSUE TITLE
URLencoded path uncorrectly stored

### ISSUE THREAD

**Issue by racciari** [open-io/oio-sds#194]
URLencoded files are uncorrectly stored when using the Swift proxy. Julien suspects a problem in oioproxy.
This is an issue when using Pydio.

**Comment by jfsmig** [comment]
Please provide a minimal script to reproduce.

**Comment by jfsmig** [comment]
:up:

**Comment by jfsmig** [comment]
:up:

**Comment by jkasarherou** [comment]
steps to reproduce:

```
❯ touch "open io"
❯ openio object create 1 oio\ x
+-------+------+----------------------------------+
| Name  | Size | Hash                             |
+-------+------+----------------------------------+
| oio x |    0 | d41d8cd98f00b204e9800998ecf8427e |
+-------+------+----------------------------------+
❯ openio object list 1
+-------+------+----------------------------------+
| Name  | Size | Hash                             |
+-------+------+----------------------------------+
| oio+x |    0 | D41D8CD98F00B204E9800998ECF8427E |
+-------+------+----------------------------------+

**Comment by jfsmig** [comment]
It becomes much better with #334 but things are not completely fixed with it.
oio-sds still needs to manage UTF-8 alias names in events sent from meta2 and meta1.

**Comment by jkasarherou** [comment]
@fvennetier status on this?

**Comment by fvennetier** [comment]
A lot of improvements have been done around UTF-8 support in user and object names. @jkasarherou The test you provided does not reproduce the bug.
