### ISSUE TITLE
LB WRAND: No rawx available 

### ISSUE THREAD

**Issue by GuillaumeDelaporte** [open-io/oio-sds#198]
Using the default lb.rawx load balancing (WRAND I think), I have some "No rawx available" errors on my platform. It occurs sometimes on a quite heavy load.
Configuration : 3 rawx and replication x3
Notice that the platform is stable, and the rawx scores are upper 50 during all the load.

I work on a little script to reproduce the problem on your env.
I will post it as soon as it will be available.

NB : When I set the lb.rawx in RR, the problem disappear.

**Comment by jfsmig** [comment]
I can't fix this quickly without breaking things.

We are completely in the fuzziness and the uncertainity described in #190.

I can propose you a patch giving quicker and better results in simple cases: no complicated distance requirements, and uniform storage class. This will help in the milestone 0.8.4 until the #190 is merged in the milestone 15.10.

**Comment by jfsmig** [comment]
The fixes planned for 15.10 are considered as not a priority.
The 15.10 is postponed to an undetermined term.
