### ISSUE TITLE
LB config output on oio-cluster

### ISSUE THREAD

**Issue by GuillaumeDelaporte** [open-io/oio-sds#199]
When you use oio-cluster, output don't show the default loadblancing configuration.

Can you put the loadblancing configuration by default in oio-cluster output ?

Like :
```
           LB(srv) : meta2=KEEP|1|1;sqlx=KEEP|1|1
           LB(meta2) : rawx = WRAND?shorten_ratio=0.600000&standard_deviation=no
```
Copyright @jfsmig

**Comment by jfsmig** [comment]
Fixed in commit 4383e3c048d5547ec67ee96f7cc85d1668789aa2.
