### ISSUE TITLE
Configuration parsing fail in account functional test

### ISSUE THREAD

**Issue by GuillaumeDelaporte** [open-io/oio-sds#208]
The configuration parser fail during functional test.

The issue appears in this two files : 
https://github.com/open-io/oio-sds/blob/master/python/tests/functional/account/test_backend.py#L24
https://github.com/open-io/oio-sds/blob/master/python/tests/functional/account/test_server.py#L25

Test setUp() try to load the file /root/.oio/sds/conf/test.conf with SafeConfigParser, but the file is in json format (produced by oio-bootstrap.sh).

Got this error : "MissingSectionHeaderError: File contains no section headers."

**Comment by jkasarherou** [comment]
We need to refactor the functional tests setUp.

**Comment by jkasarherou** [comment]
fixed in #216
