### ISSUE TITLE
Running unit tests?

### ISSUE THREAD

**Issue by GiorgioRegni** [open-io/oio-sds#209]
Hi, is there any documentation about how to run unit tests for oio-sds?

Thanks,

**Comment by jkasarherou** [comment]
Hi Georgio,
Welcome aboard :smile: 
You will find [here](https://github.com/open-io/oio-sds/wiki/Run-Tests) docs on tests. 
Feel free to regularly visit this page, it is in constant evolution.
Regards,

Julien
