### ISSUE TITLE
meta0-init: error message is not clear

### ISSUE THREAD

**Issue by jkasarherou** [open-io/oio-sds#240]
For a replicated NS, the error message is confusing:

    oio-meta0-init NS
    1445421268.550 11631 87CC log INF o.m [NS] considered as a namespace name
    1445421268.550 11631 87CC log NOT o.m META1 located from the conscience
    1445421268.612 11631 87CC log WRN o.m META0 request error (502) : Request error: delay between two meta1 assign  not respected. Try later.

**Comment by racciari** [comment]
In the same way, when you try to rerun meta0-init that already have been done, you have a werd message saying you don't have enough meta1 ...

**Comment by jkasarherou** [comment]
we currently have this message, if you rerun the `oio-meta0-init`:

```
❯ oio-meta0-init NS
643317351 1560 36F8 log INF o.m       [NS] considered as a namespace name
643317351 1560 36F8 log NOT o.m       META1 located from the conscience
643317709 1560 36F8 log WRN o.m       META0 error (502): Request error: Not enough META1 to satisfy constraints (distance, number). META0 already initiated?
```

**Comment by jkasarherou** [comment]
@jfsmig `delay between two meta1 assign  not respected` -> should we keep this feature?

**Comment by jfsmig** [comment]
@jkasarherou no!
The whole assignation logic should be moved away from the meta0 backend, to pythonic script.
