### ISSUE TITLE
Failure on object create

### ISSUE THREAD

**Issue by GuillaumeDelaporte** [open-io/oio-sds#314]
When trying to put an object I got a 500 return code, expecting 204 : 

`"POST /v3.0/NS/content/create?acct=test_account&ref=plop-0&path=2%2F4%2Fplop HTTP/1.1" 500 72`

Tracelog :

```
Dec 18 15:07:37 vagrant OIO,NS,meta1,1: 12631 3AC9 access INF 127.0.0.1:6007 127.0.0.1:57234 M1V2_SRVALL 200 0.196373 0 97E3CA9A160355A33AE3D2B6B78CE3D1A9D781A97082ABD6837A56F59D0AA787 5631273621889BC9E531E9539A3A52E7 t=0.196351 NS/test_accou nt/plop-0/meta2/2%2F4%2Fplop?1400000000000000|97E3CA9A160355A33AE3D2B6B78CE3D1A9D781A97082ABD6837A56F59D0AA787|meta2
 Dec 18 15:07:37 vagrant OIO,NS,proxy: 12630 04F1 log INF oio.proxy invalid at 2304 127.0.0.1:6007
 Dec 18 15:07:37 vagrant OIO,NS,proxy: 12630 04F1 access INF 127.0.0.1:6002 127.0.0.1:35975 POST 500 0.197360 72 - /v3.0/NS/content/create?acct=test_account&ref=plop-0&path=2%2F4%2Fplop t=0.197331
```

Way to reproduce it in a single mode environment : 
`nosetests functional/container/test_container.py:TestMeta2Functional.test_list`

**Comment by jfsmig** [comment]
Can you please provide the body you sent in the POST request ?

**Comment by jkasarherou** [comment]
I can't reproduce it, @jfsmig any ideas?

**Comment by GuillaumeDelaporte** [comment]
@jfsmig check your own code to check the body of POST request : https://github.com/open-io/oio-sds/blob/master/python/tests/functional/container/test_container.py#128

**Comment by jkasarherou** [comment]
Any chance this is caused by timeout?

**Comment by jkasarherou** [comment]
#316 should help

**Comment by jfsmig** [comment]
#316 made the trick !
