### ISSUE TITLE
Log format conscience

### ISSUE THREAD

**Issue by GuillaumeDelaporte** [open-io/oio-sds#371]
According to the log format white paper, the following line does not match :

```2016-01-18T17:05:21.930880+00:00 bench-node1 OIO,OPENIO,conscience,0: info 32280 1AC0 access INF 10.0.0.230:6000 10.0.0.231:42436 0.0002 703432303831353546363043423341454334433133353846353445443133413445 REQ_GET_SRV [NS=OPENIO] 200 OK```

Request and response code aren't at the right place, and the response size is missing. Should be something like

```2016-01-18T17:05:21.930880+00:00 bench-node1 OIO,OPENIO,conscience,0: info 32280 1AC0 access INF 10.0.0.230:6000 10.0.0.231:42436 REQ_GET_SRV 200 0.0002 0 703432303831353546363043423341454334433133353846353445443133413445 [NS=OPENIO] OK```

Finally what means the code `703432303831353546363043423341454334433133353846353445443133413445` ?
At this place, you should have the "user id" and the "unique request id"

**Comment by jfsmig** [comment]
:checkered_flag: Please check if the format fits, now that #389 has been merged.

**Comment by GuillaumeDelaporte** [comment]
This is awesome :horse:
