### ISSUE TITLE
meta1: wrong error code on link

### ISSUE THREAD

**Issue by jkasarherou** [open-io/oio-sds#422]
On a link request, when no service is available we have this error:
```
META1 error: Request error: Query error: type [oiofs] not managed (HTTP 500) (STATUS 453)
```

should be `CODE_POLICY_NOT_SATISFIABLE = 481` ?

**Comment by fvennetier** [comment]
This used to happen when no service of the specified type ever registered to Conscience. If you register a service then shut it down, you will actually get code 481.
> (code=481) META1 error: Request error: Query error: No service available

Now that services are registered by conscience-agent (even if they are down), this should not happen anymore.
