### ISSUE TITLE
Return tag.vol from metaX services in oio-proxy 

### ISSUE THREAD

**Issue by racciari** [open-io/oio-sds#481]
RawX services returns the volume used using oio-proxy. Please add the same to all services (esp. metaX).
Requests: `curl -XGET 'http://172.16.139.1:6006/v3.0/SCALAIR/local/list'`
Current output:
`"ns":"SCALAIR","type":"meta2","addr":"172.16.139.1:6023","score":99,"tags":{"stat.space":99.984016,"stat.cpu":98.443439,"stat.io":100.000000,"tag.up":true}}`

**Comment by jfsmig** [comment]
The `tag.vol` is a part of the service's registration. Now it is performed by the `oio-conscience-agent`, this is the tight place to add this tag.

**Comment by fvennetier** [comment]
This tag is currently set by the _rawx_ plugin (the value is fetched from rawx `/stat` request) but can be moved to the _volume_ plugin (the value can be fetched from the configuration file).

**Comment by jfsmig** [comment]
Fixed for release-2.0  in #485

**Comment by jfsmig** [comment]
Fixed for master in #489
