### ISSUE TITLE
[account] Cannot trust the informations in the account for the containers

### ISSUE THREAD

**Issue by sebastienlapierre** [open-io/oio-sds#496]
The informations in the account don't reflect the reality of this one.
It shows containers that don't exist and a wrong size of them.

**Reproducible every time during a bench even tiny.**
cmd: openio --oio-ns _NS_ --oio-account _account_name_ container list

**Comment by jfsmig** [comment]
@sebastienlapierre: do you consider this as fixed or not ?

**Comment by jkasarherou** [comment]
what about now? @sebastienlapierre
