### ISSUE TITLE
openio-sds Vagrant boxes can't install openstack-juno

### ISSUE THREAD

**Issue by dwjfk** [open-io/oio-sds#584]
The include files for the openio-sds VirtualBox Vagrant setup are attempting to install openstack -juno from repos.fedorapeople.org, which has been deprecated. 
Error: Execution of '/bin/yum -d 0 -e 0 -y list https://repos.fedorapeople.org/repos/openstack/openstack-juno/rdo-release-juno-1.noarch.rpm' returned 1: Error: No matching Packages to list

Maybe move it up to Kilo?

**Comment by racciari** [comment]
Hey,
thank you for the report, I updated the package to Mitaka in this patch https://github.com/open-io/puppet-openiosds/commit/d66ccfc4165e7684e9680a4ef799585765d1949c
It should be working now !

**Comment by dwjfk** [comment]
Great, I am testing it now. 
I also ran into some trouble with the SDS software. OIO-meta-servers seem to be binding to IP addresses that are not routeable (docker resides on those server, so I get 172.17.0.1 all the time). Is there a fix for this?
