### ISSUE TITLE
openio: integrate zk-bootstrap.py

### ISSUE THREAD

**Issue by racciari** [open-io/oio-sds#614]
Integrate zk-bootstrap.py to the `openio directory bootstrap` command.

**Comment by fvennetier** [comment]
I like idea of integrating all operations as subcommands of `openio`. Unfortunately we get more and more complaints about the slowness of this program, and I'm considering splitting it to reduce its loading time.

**Comment by jfsmig** [comment]
Could we just wrap (execute) the zk-bootstrap.py and zk-reset.py scripts ?
This would lead to dummy sub-command without dependency, even if the wrapped zk-bootstrap.would become as slow as openio to start.

**Comment by jfsmig** [comment]
Done in PR #1650
