### ISSUE TITLE
Wiki page for Ubuntu installation is not updated

### ISSUE THREAD

**Issue by ottuzzi** [open-io/oio-sds#644]
Hi,

   I tried to install openio on Ubuntu 14.04 Trusty because in the wiki page[1] it seems that this is a supported ubuntu version.
If I follow the docs I see:

    root@vm128:~# apt-get install openio-sds
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    E: Unable to locate package openio-sds

Checking in the repository I see there are no packages for Ubuntu Trusty: can you provide packages for it? 

Thanks
Bye
Piero

[1]https://github.com/open-io/oio-sds/wiki/Debian---Ubuntu

**Comment by racciari** [comment]
Hi,
we used to support Ubuntu Trusty until the new LTS was released (Xenial), and we did not plan to support Trusty anymore.
Our wiki page wasnt very clear about it, I updated it.
Sorry for the packages, I really encourage you to try on Ubuntu Xenial, we will be happy to support you for the install!

**Comment by ottuzzi** [comment]
OK,

   thank you very much for fixing wiki.

Closing issue.

Bye
Piero
