### ISSUE TITLE
Problem with Debian Jessie packages

### ISSUE THREAD

**Issue by ottuzzi** [open-io/oio-sds#646]
Hi,

   following the guide in [1] I tried to install on Debian Jessie:

    root@vm129:~# apt-get install openio-sds
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:

    The following packages have unmet dependencies:
     openio-sds : Depends: python-requests (>= 2.6.0) but 2.4.3-6 is to be installed
    E: Unable to correct problems, you have held broken packages.

Can you help?
Thanks
Bye
Piero
[1]https://github.com/open-io/oio-sds/wiki/Debian---Ubuntu

**Comment by ottuzzi** [comment]
Hi,

   please keep this issue in standby: I have to verify if jessie-backports repository was enabled (I think not :))

Thanks
Bye
Piero

**Comment by racciari** [comment]
Hi,

yes, its available in [Jessie Backports](https://packages.debian.org/search?keywords=python-requests&searchon=names&section=all&suite=jessie-backports) ;-)
I have updated the documentation.

Thanks again!

**Comment by ottuzzi** [comment]
Thank you
