### ISSUE TITLE
OIO Swift3 install

### ISSUE THREAD

**Issue by gigzbyte** [open-io/oio-sds#650]
Hello all!
I'm trying to install openio sds cluster. My target is to get private S3-compatible distributed cloud service.
First of all, i use this guide and get working solution.
http://docs.openio.io/install-guide-centos/installation.html
After this i want to enable S3 layer. And i follow this guide:
https://github.com/open-io/oio-sds/wiki/Install-Guide---OpenIO-Swift-S3-gateway
When i start puppet, it changes /etc/keystone/keystone.conf - change this setting:
`# Keystone Token persistence backend driver. (string value)
driver=sql
Keystone catalog backend driver. (string value)
driver=sql`
And i get this error:
`CRITICAL keystone [-] ImportError: Class sql cannot be found`
Also it changes 'provider=uuid' setting, and it produces:
`Class uuid cannot be found`
And keystone service doesn't start and install interrupts.
If i fix this settings to the correct:
` # Keystone Token persistence backend driver. (string value)
driver=keystone.token.backends.sql.Token
 # Keystone catalog backend driver. (string value)
driver=keystone.token.backends.sql.Token`
Keystone starts OK.
But then i've got errors about Keystone API mismatches:
`Error: /Stage[main]/Keystone/Exec[keystone-manage bootstrap]: Failed to call refresh: keystone-manage bootstrap --bootstrap-password wfefwewefwef returned 2 instead of one of [0]
Error: /Stage[main]/Keystone/Exec[keystone-manage bootstrap]: keystone-manage bootstrap --bootstrap-password wfefwewefwef returned 2 instead of one of [0]
Notice: /Stage[main]/Keystone::Deps/Anchor[keystone::service::begin]: Triggered 'refresh' from 2 events
Notice: /Stage[main]/Keystone::Service/Service[keystone]: Triggered 'refresh' from 1 events
Notice: /Stage[main]/Keystone::Deps/Anchor[keystone::service::end]: Triggered 'refresh' from 1 events
Error: /Stage[main]/Keystone::Roles::Admin/Keystone_user[admin]: Could not evaluate: Execution of '/usr/bin/openstack user show --format shell admin --domain default' returned 2: usage: openstack user show [-h]
                           [-f {html,json,json,shell,table,value,yaml,yaml}]
                           [-c COLUMN] [--max-width <integer>] [--noindent]
                           [--prefix PREFIX]
                           <user>
openstack user show: error: unrecognized arguments: --domain default
Error: Could not prefetch keystone_service provider 'openstack': Execution of '/usr/bin/openstack service list --quiet --format csv --long' returned 2: usage: openstack service list [-h]
                              [-f {csv,html,json,json,table,value,yaml,yaml}]
                              [-c COLUMN] [--max-width <integer>] [--noindent]
                              [--quote {all,minimal,none,nonnumeric}]
openstack service list: error: unrecognized arguments: --long
Error: Not managing Keystone_service[openio-swift] due to earlier Keystone API failures.
Error: /Stage[main]/Main/Keystone_service[openio-swift]/ensure: change from absent to present failed: Not managing Keystone_service[openio-swift] due to earlier Keystone API failures.
Error: /Stage[main]/Main/Keystone_user[demo]: Could not evaluate: Execution of '/usr/bin/openstack user show --format shell demo --domain default' returned 2: usage: openstack user show [-h]
                           [-f {html,json,json,shell,table,value,yaml,yaml}]
                           [-c COLUMN] [--max-width <integer>] [--noindent]
                           [--prefix PREFIX]
                           <user>
openstack user show: error: unrecognized arguments: --domain default`
Please, what am i doing wrong?
Thank you for all your help!

**Comment by racciari** [comment]
Hi,

I suspect you are not using the correct puppet module for Mitaka (version 7.0.0 on Puppet Forge).
You can verify by listing your installed modules:
`# puppet module list`

**Comment by jfsmig** [comment]
No news means good news.

Feel free to re-open if still active.
