### ISSUE TITLE
The LB allows too many polls on the same host

### ISSUE THREAD

**Issue by jfsmig** [open-io/oio-sds#660]
This happens when polling services on small deployments, e.g.:
- you deploy 3 hosts witch each 9 rawx
- you require 9 rawx

The LB ensures each host will we selected at least once, but doesn't ensure the chunks 4 -> 9 will be faned out fairy among the hosts.

This is somewhere between the bug and the enhancement, so I place both tags.

**Comment by jfsmig** [comment]
The game of locations masks, currently shifted to progressively reduce the constraints on the LB, is obviously too weak.

The key idea is to avoid trying to deduce information that the administrator **knows**.

I propose to let the administrator configure locations the old way, *i.e.* explaining a hierarchy like `token (separator token)*` (e.g. "site.room.bay.host"). This is something easy for the administrator that can configure its tools to inform each service with its location. The services themselves cannot deduce it, e.g.  when insulated in containers they cannot even rely on the IP or PORT they know.
* require from the admin a location and do not try to deduce it
* require uniform locations across the service so that we can compare them
* map each `token` into a portion of the location. Whatever how we do this, either with explicit hexadecimal characters or hashing the token string
* allow one level of "mask degradation" for each hierarchy level, i.e. for each portion of the location mask
* ignore the meaning of each token
* limit the possible depth of the hierarchy, because the location have a fixed size.

This is the only way I imagine to have the current piece of code manage as well minimal installations (with few hosts each carrying dozens of services) as huge installations with a lot of independent mono-disk hosts.

**Comment by racciari** [comment]
Yes

**Comment by fvennetier** [comment]
This should be fixed in most cases by #1022 and #1036.
