### ISSUE TITLE
oio.api.object_storage.object_create() throwing error InvalidStorageMethod

### ISSUE THREAD

**Issue by rohanil** [open-io/oio-sds#682]
I tried to do this:

`obj1 = storage.object_create("my_account", "test_container", obj_name="object0", data="data")`

And raises following exception:

`oio.common.exceptions.InvalidStorageMethod: need more than 1 value to unpack`

Traceback:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "oio/api/object_storage.py", line 68, in _wrapped
    return fnc(self, account, container, *args, **kwargs)
  File "oio/api/object_storage.py", line 318, in object_create
    key_file=key_file)
  File "oio/api/object_storage.py", line 501, in _object_create
    storage_method = STORAGE_METHODS.load(sysmeta['chunk_method'])
  File "oio/common/storage_method.py", line 45, in load
    raise exc.InvalidStorageMethod(str(e))
oio.common.exceptions.InvalidStorageMethod: need more than 1 value to unpack`

**Comment by jkasarherou** [comment]
Hello rohanil,
which version of the server and the API are you using for your test?

**Comment by jfsmig** [comment]
:up: @rohanil :smile:

**Comment by jfsmig** [comment]
This has been fixed, in a time prior to commit 7be03de788f83b8d29c7c8ca3493c0e525b2aa65.
Please, consider upgrading.
