### ISSUE TITLE
Proxyd: conscience/unlock asking a score

### ISSUE THREAD

**Issue by Crashdown59** [open-io/oio-sds#688]
with curl:

```curl -X POST 'http://127.0.0.1:6000/v3.0/OPENIO/conscience/unlock' --data "{'type':'rawx', 'addr':'127.0.0.1:6012'}"```

The result is : 
```{"status":400,"message":"JSON error: Missing field [score]"}```

**Comment by fvennetier** [comment]
Fixed by #693
