### ISSUE TITLE
Unlock of services needs to be performed many times

### ISSUE THREAD

**Issue by GuillaumeDelaporte** [open-io/oio-sds#690]
Using this documentation http://docs.openio.io/install-guide-centos, when comes the step of unlocking services (number 6 of the section" Initialize OpenIO Namespace"), I need to launch this command `oio-cluster -r OPENIO | xargs -n1 oio-cluster --unlock-score -S` many times to be sure that every services will be unlocked.

The command doesn't work at the first time.

**Comment by jfsmig** [comment]
You probably encounter cache effects. Several ways exist to work around, specially when initiating a platform:
* add an explicit reload of the proxy in the unlock-all command.
* use a CLI tool to send the unlock then wait for effective unlocking (such a tool exists for development purposes but it is not distributed: oio-wait-scored.sh)
