### ISSUE TITLE
Test gridclient.h : trying to link a service and an already linked reference

### ISSUE THREAD

**Issue by Reaskel** [open-io/oio-sds#72]
When using the function hc_force_service and trying to link a new service with a reference I already linked before, I got the following error message :

(code=502) Error code not managed <502> : Handling: Request error: (SQLITE_CONSTRAINT) columns cid, srvtype, seq are not unique

It indicates that my new service has been denied because it looks like an existing service already linked to the reference.
However, in my code, I have already linked the reference with three services whose url respectively ends with 6010/6011/6012. The new service url has indeed the same cid and srvtype but ends with 6048.

The same test with an unlinked reference works perfectly.

Am I missing something like a restriction in that function’s use ? Is it a bug ?

**Comment by jfsmig** [comment]
Did you try the option mentionned at https://github.com/open-io/oio-sds/tree/master/proxy#services-actions-dirnsreftypeaction ?
I.e. using a header to allow replacing the previous information: "X-oio-action-mode: replace"

**Comment by Reaskel** [comment]
I just tried it and effectively it works, thank you ! I just didn't see you added that option in the last readme update.
However, wouldn't it be better if in case of that header is forgot, the fonction handles the exception with a 400 message rather than returning error code 502 not managed ?

**Comment by jkasarherou** [comment]
The returned code is not yet managed, still in 500.

**Comment by jfsmig** [comment]
The client has been removed.
