### ISSUE TITLE
API: Set quota on container

### ISSUE THREAD

**Issue by GuillaumeDelaporte** [open-io/oio-sds#727]
Can you add a command like `openio container set quota` to be able to modify the global namespace configuration at the container level (maybe account as well?)?

Should be great to implement it also in the Python/Java/C APIs.

**Comment by fvennetier** [comment]
While there is no CLI to set it, you can make requests to the proxy:
`curl -XPOST "http://localhost:6000/v3.0/NS/admin/set_properties?ref=CT&type=meta2&acct=myaccount" -d '{"system": {"sys.m2.quota": "58000000"}}'`.

**Comment by jfsmig** [comment]
Fixed in #784
