### ISSUE TITLE
Test grid_client.h : Can’t change a content property with hc_set_content_property

### ISSUE THREAD

**Issue by Reaskel** [open-io/oio-sds#73]
After having used the hc_set_content_property to put a property to a content e.g. “key1=value1”, I tried to modify the value by calling again the hc_set_content_property on the content, with the parameter “key1=value2”.
When I tried to get the key1 value from that content, the calling function returned value1.
So set_content_property doesn’t change the value of an existing property.

Is it a bug or is the set_content function designed to run that way ?

**Comment by jfsmig** [comment]
The client has been removed
