### ISSUE TITLE
Allow reads on a service when the score reaches 0

### ISSUE THREAD

**Issue by GuillaumeDelaporte** [open-io/oio-sds#730]
Since we are taking care of the score for the read operation, a problem appeared with the 0 score.

Indeed, a 0 score doesn't necessarily mean that the service is down. If we think about the rawx, when a volume reaches his maximum (95% by default), the score is set to 0. As a consequence, we don't read data on it anymore.

One idea is to have two different scores, one for the read and one for the write to avoid this issue.

**Comment by jfsmig** [comment]
It is currently possible to read a content with any chunk stored on a services with a score of 0. The score=0 will be used as a low priority more than a "stop sign".
