### ISSUE TITLE
oio-event-agent: Account problem during heavy write load and mass delete

### ISSUE THREAD

**Issue by sebastienlapierre** [open-io/oio-sds#733]
During and after heavy write load or mass delete, the information in Account (containers and number of contents) become false.

There are several errors reported in oio-event-agent:

> 2016-10-13T15:46:09.816176+02:00 sasopenio01 OIO,SCALAIR,oio-event-agent,0: warning  11490 2ED4050 log WARNING no handler found for {'url': {'account': 'scalair_account', 'ns': 'SCALAIR', 'type': 'meta2', 'user': 'slappy_180', 'id': 
> '637D3E0CDC4B7273F45B6CD8B5668A684F4ABE78674D463378199C64547D2CD1'}, 'data': [{'host': '172.16.139.1:6024', 'args': u'', 'type': 'meta2', 'seq': 1}, {'host': '172.16.139.2:6023', 'args': u'', 'type': 'meta2', 'seq': 1}, {'host': '172.16.139.3:6023', 'args': u'', 'type': 'meta2', 'seq': 1}], 'when': 1476366369815691, 'event': 'account.services', 'job_id': '8437336'}
> 
> 2016-10-13T15:50:58.949234+02:00 sasopenio01 OIO,SCALAIR,oio-event-agent,0: warning  11500 2ED49B0 log WARNING error while deleting chunk http://172.16.139.1:6032/0B0D8A269A0F670A2B50C7E634D99878C844276E4818C89BE7194EDCEDC4E568 ""
> 
> 2016-10-13T15:50:58.956058+02:00 sasopenio01 OIO,SCALAIR,oio-event-agent,0: warning  11463 2ED4050 log WARNING beanstalk connection error
> 
> 2016-10-13T15:50:59.028953+02:00 sasopenio01 OIO,SCALAIR,oio-event-agent,0: err  11500 2ED4690 log ERROR Error: An error occured#012Traceback (most recent call last):#012  File "/usr/lib/python2.7/site-packages/oio/event/handlers/base.py", line 19, in **call**#012    return res(env, cb)#012  File "/usr/lib/python2.7/site-packages/oio/event/evob.py", line 50, in **call**#012    cb(self.status, self.body)#012  File "/usr/lib/python2.7/site-packages/oio/event/consumer.py", line 228, in cb#012    beanstalk.delete(job_id)#012  File "/usr/lib/python2.7/site-packages/oio/event/beanstalk.py", line 470, in delete#012    self.execute_command('delete', job_id)#012  File "/usr/lib/python2.7/site-packages/oio/event/beanstalk.py", line 426, in execute_command#012    return self.parse_response(connection, command_name, **kwargs)#012  File "/usr/lib/python2.7/site-packages/oio/event/beanstalk.py", line 432, in parse_response#012    response = connection.read_response()#012  File "/usr/lib/python2.7/site-packages/oio/event/beanstalk.py", line 321, in read_response#012    response = self._parser.read_response()#012  File "/usr/lib/python2.7/site-packages/oio/event/beanstalk.py", line 147, in read_response#012    response = self._buffer.readline()#012  File "/usr/lib/python2.7/site-packages/oio/event/beanstalk.py", line 95, in readline#012    self._read_from_socket()#012  File "/usr/lib/python2.7/site-packages/oio/event/beanstalk.py", line 74, in _read_from_socket#012    (e.args,))#012ConnectionError: Error while reading from socket: ('Connection closed by server.',)

**Comment by jfsmig** [comment]
A lot of improvements have been made since then. Better timeout management, retries, etc.
Please, @sebastienlapierre can you retry with an updated OpenIO SDS platform ?

**Comment by fvennetier** [comment]
#1017 and #1026 should have fixed this problem. Can you confirm these problems do not happen anymore with 4.0.0.b1?
