### ISSUE TITLE
Why does the SVC monitor use "select(0, NULL, NULL, &sleep_time)" ?

### ISSUE THREAD

**Issue by conradkleinespel** [open-io/oio-sds#74]
Hello :-)

I'm looking through the source to improve error reporting within the SVC monitor tool, because I have errors when it tries to start Apache but these errors are not logged anywhere, from what I can see. Is that correct ?

Anyway, I noticed the svc-monitor seems to use `select (2)`, as [can be seen here](https://github.com/open-io/oio-sds/blob/d59e5dabad59047c7a8d8370d9149762d9b0b8ef/svc-monitor/main.c#L297), for something where I'm thinking a simple call to `sleep (3)` would be appropriate.

What is the reason behind that ?

Thanks for your help,
Best regards,
Conrad

**Comment by jfsmig** [comment]
Calling select() with no descriptor set is a way to sleep with a microsecond precision. When returning, you also know if select() slept the whole time or has been interrupted. Using pselect() brings nanosecond precision and the ability to filter the signals you expect.

Thanks for pointing it, in this case a call to sleep/usleep/nanosleep was really enough and clearer.

**Comment by jfsmig** [comment]
Fixed in e4bd251a4610984f52c40d182a23229b29b25b6f, merged in #90.

**Comment by conradkleinespel** [comment]
Alright, great, thanks for the explanations ! :+1:
