### ISSUE TITLE
`openio object create` might hang in case of a split brain

### ISSUE THREAD

**Issue by jfsmig** [open-io/oio-sds#816]
It seems that the `openio` CLI tool hangs indefinitely when trying to reach a RAWX that has been polled despite the split brain (see #815).
All the attempts to the unreachable site have failed, then the process waits something that never happens.
Reported by @gdelafond.

**Comment by jfsmig** [comment]
Happens with commit 331ea7a

**Comment by jkasarherou** [comment]
I'll dig into this
