### ISSUE TITLE
Add IP:PORT for each request line for openio --debug

### ISSUE THREAD

**Issue by gdelafond** [open-io/oio-sds#821]
With `openio -v --debug object create my container test.zero` the debug does not display on which server the request is done: 
```
Starting new HTTP connection (1): 127.0.0.1
"POST /v3.0/TEST/content/prepare?acct=TEST&ref=mycontainer&path=test.zero HTTP/1.1" 200 537
"POST /v3.0/TEST/content/prepare?acct=TEST&ref=mycontainer&path=test.zero HTTP/1.1" 200 537
```

I think we should have the IP:PORT before the request: 
```
192.168.0.52:6025 "POST /v3.0/TEST/content/prepare?acct=TEST&ref=mycontainer&path=test.zero HTTP/1.1" 200 537
192.168.0.65:6025 "POST /v3.0/TEST/content/prepare?acct=TEST&ref=mycontainer&path=test.zero HTTP/1.1" 200 537
```

**Comment by AymericDu** [comment]
Since `urllib3` >= `1.17` (and so `requests` >= `2.12.0`), the debug display the host and the port.

See https://github.com/shazow/urllib3/commit/9a3e0aa516948c854225febe889f2cdc50b6adcc and https://github.com/requests/requests/commit/99fa7becf263473c7bfc1998b41c2c6c80a0f499

**Comment by jfsmig** [comment]
Thank you, @AymericDu !
