### ISSUE TITLE
Proxy/meta2 : segfault on content put with invalid headers

### ISSUE THREAD

**Issue by Reaskel** [open-io/oio-sds#83]
The put content function needs two mandatory headers to run : 'x-oio-content-meta-hash' and 'x-oio-content-meta-length'. If the given hash header is somehow incoherent, sending the put request entails a segfault and the proxy crashes.

**Comment by jfsmig** [comment]
Can you please check the test now pass with the up-ot-date master (commit 005cb1ba609d26e0ae3e3662830b1f26aeadd769) ?

**Comment by Reaskel** [comment]
The issue is fixed, thanks @jfsmig
