### ISSUE TITLE
proxy: set properties with no properties fail

### ISSUE THREAD

**Issue by jkasarherou** [open-io/oio-sds#830]
When setting properties on a container with no properties we have:

```
No properties found in JSON object (HTTP 400) (STATUS 400)
```

For a content we have:

```
Bad "properties" field (HTTP 400) (STATUS 400)
```

This **new** behavior is problematic for oioswift open-io/oio-swift#31

**Comment by fvennetier** [comment]
I makes no sense to call `set_properties` if you don't provide properties. I such case, I expect an error.
