### ISSUE TITLE
Confusing error message when performing directory bootstrap

### ISSUE THREAD

**Issue by vdombrovski** [open-io/oio-sds#832]
Issue
---
I'm getting a confusing error message when running the command

```sh
/usr/bin/openio directory bootstrap --replicas 3 --oio-ns=test
integer division or modulo by zero
```

Context
---
- Deployed a cluster of 3 nodes (using puppet) following the documentation as it is described [here](http://docs.openio.io/install-guide-centos/installation.html).

```sh
# openio cluster list --oio-ns test
+---------+--------------------+--------+----------+-------+-------+-------+
| Type    | Id                 | Volume | Location | Slots | Up    | Score |
+---------+--------------------+--------+----------+-------+-------+-------+
| account | 192.168.50.41:6068 | n/a    | openio01 | n/a   | True  |    95 |
| account | 192.168.50.43:6068 | n/a    | openio03 | n/a   | True  |    97 |
| account | 192.168.50.42:6074 | n/a    | openio02 | n/a   | True  |    10 |
| meta1   | 192.168.50.41:6065 | n/a    | openio01 | n/a   | False |     0 |
| meta1   | 192.168.50.43:6065 | n/a    | openio03 | n/a   | False |     0 |
| meta1   | 192.168.50.42:6071 | n/a    | openio02 | n/a   | False |     0 |
| meta0   | 192.168.50.41:6064 | n/a    | openio01 | n/a   | False |     0 |
| meta0   | 192.168.50.43:6064 | n/a    | openio03 | n/a   | False |     0 |
| meta0   | 192.168.50.42:6070 | n/a    | openio02 | n/a   | False |     0 |
+---------+--------------------+--------+----------+-------+-------+-------+
```

- Ran the *zk-bootstrap.py* command that also succeeded.

- When trying to unlock the scores before the directory bootstrap, MetaX scores stay at 0

- Finally, when trying to run the directory bootstrap command, the message described above appears.

I would assume, the error is due to 0 meta0 services detected, resulting in this error, still is it possible to provide a more comprehensible error message in this case?

**Comment by fvennetier** [comment]
Is this the same as https://github.com/open-io/oio-sds/issues/790?

**Comment by fvennetier** [comment]
Can you run your command again with `-v --debug` so we can see from where the message comes?

**Comment by fvennetier** [comment]
Any update on this?

**Comment by vdombrovski** [comment]
Having retried using 3.2.0, I can't reproduce this issue.

**Comment by fvennetier** [comment]
Bug reappeared with bf5a83c9f.
