### ISSUE TITLE
oio-tool ping to output as "perfdata"

### ISSUE THREAD

**Issue by racciari** [open-io/oio-sds#836]
It would be great to have the output of the command like described in the [Shinken plugin output](http://shinken.readthedocs.io/en/latest/15_development/pluginapi.html#development-pluginapi).

For example:
`# oio-tool ping 172.17.25.7:6103
OK 0.000439s`
Changed by:
`# oio-tool ping 172.17.25.7:6103
OK 0.439 ms | 0.439`

**Comment by vdombrovski** [comment]
I would like to provide more details concerning the Nagios format for performance data, to elaborate on what @racciari posted.

First and foremost, in Shinken (and Nagios) is considered "perfdata" the part **after the pipe**.

After the pipe, there should be one or several **named metrics**. Each metric is followed by either a single value, or a pattern that matches a specific format.

e.g: `oio-tool ping 172.17.25.7:6103 OK 0.439 ms | time=0.439`

The full format is as follows:

`[METRIC_NAME]=[METRICVALUE][UNIT];[WARNING_VALUE];[CRIT_VALUE];[MIN];[MAX]`

For this format to work properly, all 7 field must be present. Any field can be left empty, such as in the following example (taken from Nagios Monitoring Plugins - check_tcp command):

```sh
/usr/lib/monitoring-plugins/check_tcp -H 192.168.50.41 -p 6001
TCP OK - 0.000 second response time on 192.168.50.41 port 6001|time=0.000310s;;;0.000000;10.000000
```

Here the metric name is time, then we have the value, the unit (s), the min and the max, but the critical and warning values have been left empty.

Finally, there may be several metrics reported; those need to be provided in the output, separated by a space character:

e.g. `OK | metric1=0.4 metric2=0.7`


Here is a [link to the actual python code](http://shinken.readthedocs.io/en/latest/_modules/shinken/misc/perfdata.html)  used by shinken as part of its perfdata module to parse the incoming command output.
