### ISSUE TITLE
Proxy/meta1 : cleaning the meta1 cache between tests

### ISSUE THREAD

**Issue by Reaskel** [open-io/oio-sds#84]
The present tests on meta1 linking functions can't be perfectly run as long as there is no way to clean the meta1 cache before each test.
Indeed, those tests often reach a point where a lot of services, which were used during previous tests and couldn't be deleted from the meta1, take the place of currently used services and make unexpected results.

Is it possible to improve that situation ?

**Comment by jfsmig** [comment]
fixed ... several commits ago.
