### ISSUE TITLE
Meta2 cache issue when recreating a container

### ISSUE THREAD

**Issue by sebastienlapierre** [open-io/oio-sds#848]
Sometimes, when I recreate a container with the same name I have this error:
```
[root@sasopenio01 ~]# openio container create slappy_162
Request error: Peers resolution error: get_peers(24C4C9B739AF0C77CBA83673814B797449E1D7CDF908E355631349D3856F678D.1,meta2): Base not managed (HTTP 403) (STATUS 431)
```

Even if i restart the oioproxy.
I need to restart meta2 service to fix this problem.

**Comment by fvennetier** [comment]
Very hard to reproduce without messing with the process with GDB or `kill -STOP`. There are already 2 decache orders when the database is destroyed. If this happens again, you can clear the cache of the faulty service with a call like
`curl -v -XPOST "http://127.0.0.1:6000/v3.0/forward/flush?id=127.0.0.1:6014"`
 (with 127.0.0.1:6014 being the id of the faulty service).

**Comment by jfsmig** [comment]
Closed because of no other report since 5 months, thanks to numerous fixes.
