### ISSUE TITLE
A rawx is polled in place of a rawx (/lb/poll)

### ISSUE THREAD

**Issue by jfsmig** [open-io/oio-sds#854]
It happens when the namespace is configured with a service_update_policy presenting a `A=...|...|...|user_is_a_service=B` option for a service-type A. When polling a service of type `A`, a service of type `B` will also be polled.

```
# oio-reset.sh -v -f etc/bootstrap-preset-smallrepli.yml -f etc/bootstrap-udp.yml

# grep service_update_policy ~/.oio/sds/conf/OPENIO-conscience-1.conf 
param_option.service_update_policy=meta2=KEEP|3|1;sqlx=KEEP|1|1|;rdir=KEEP|1|1|user_is_a_service=rawx

# curl -v -XPOST "127.0.0.1:6000/v3.0/OPENIO/lb/poll?pool=rdir"
[{"addr":"127.0.0.1:6022","id":"OPENIO|rawx|127.0.0.1:6022"},{"addr":"127.0.0.1:6024","id":"OPENIO|rdir|127.0.0.1:6024"}]
```

**Comment by fvennetier** [comment]
This is the intended behavior for this route: choose a pair of services not on the same location (you are supposed to provide the id of the `rawx` service). If you want only an `rdir` service without location constraints, use `/lb/choose?type=rdir`.

**Comment by jfsmig** [comment]
"It makes me a pretty leg". :disappointed: 
This is not intuitive, and seems less intentional than subsequent to a technical artifice.

To be complete, there is general review to give here. Meanwhile, is there a way to "just translate" the "user_is_service" behaviour with a common request with locations/services to avoid?
