### ISSUE TITLE
Services disappear from the openio cli after a server crashes

### ISSUE THREAD

**Issue by sebastienlapierre** [open-io/oio-sds#874]
A server crashes, after a certain amount of time, 
The services are neither displayed in false nor scored at zero, they just disappear from the openio cli.
It is therefore very difficult to find any information about them (as long as the server is down), for example to start a data reconstruction.

**Comment by sebastienlapierre** [comment]
We must no longer withdraw the services of conscience automatically, this must remain a manual intervention.
This to prevent the loss of important information.

**Comment by sebastienlapierre** [comment]
An other thing in this case, if i try to retrieve the rawx/rdir repartition i had the following problème:
`root@admin1[ac157](openio):~/OpenIOSDS/puppet_files# openio volume admin bootstrap  --oio-ns AQUARAY
u'AQUARAY|rdir|172.20.0.67:6626'`

I can't find the assignments rdir / rawx...

**Comment by fvennetier** [comment]
@sebastienlapierre Can you run the command again with the `--debug` option, so I can see from which line the exception is raised? @racciari got the same error but I did not copy the traceback.

**Comment by sebastienlapierre** [comment]
here it is: `root@admin1[ac157](openio):~/OpenIOSDS/puppet_files# openio volume admin bootstrap  --oio-ns AQUARAY --debug
Starting new HTTP connection (1): 127.0.0.1
Starting new HTTP connection (1): 127.0.0.1
u'AQUARAY|rdir|172.20.0.67:6626'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cliff/app.py", line 374, in run_subcommand
    result = cmd.run(parsed_args)
  File "/usr/lib/python2.7/dist-packages/cliff/display.py", line 92, in run
    column_names, data = self.take_action(parsed_args)
  File "/usr/lib/python2.7/dist-packages/oio/cli/admin/volume.py", line 197, in take_action
    all_rawx = self.app.client_manager.admin.volume.assign_all_rawx()
  File "/usr/lib/python2.7/dist-packages/oio/rdir/client.py", line 36, in assign_all_rawx
    self._lookup_rdir_host(resp))]
KeyError: u'AQUARAY|rdir|172.20.0.67:6626'
Exception raised: u'AQUARAY|rdir|172.20.0.67:6626'`
