### ISSUE TITLE
When no connection to the conscience, oio-cluster replies with a shitty error

### ISSUE THREAD

**Issue by racciari** [open-io/oio-sds#877]
# oio-cluster NAMESPACE
Failed to get namespace info: (0) Request error (403): No error explained

**Comment by racciari** [comment]
Happened on an environment where http_proxy/https_proxy are set, we need to avoid the env proxy settings!

**Comment by jkasarherou** [comment]
oio-cluster is not deprecated tool?

**Comment by jfsmig** [comment]
Deprecated or not, all the C http requests are based on libcurl, and we do not properly prevent the `http_proxy` from ENV to be taken into account.
On the way to be fixed!

**Comment by jfsmig** [comment]
Fixed in #885
