### ISSUE TITLE
directory bootstrap failure

### ISSUE THREAD

**Issue by jkasarherou** [open-io/oio-sds#899]
`Body contains non printable characters at offset 4194313 (HTTP 400) (STATUS 400)`

**Comment by jfsmig** [comment]
Do we have more information about this ?
Did it happen in the body sent to the `oio-proxy` or in the body received from it ?

**Comment by jkasarherou** [comment]
command also takes a while before failure

**Comment by jkasarherou** [comment]
Happens when only 2 meta0, meta1 instead of 3
