### ISSUE TITLE
improve error output for blob-rebuilder

### ISSUE THREAD

**Issue by jkasarherou** [open-io/oio-sds#914]
`2017-03-16T11:10:53.552665+02:00 node1 OIO,RELEX,blob-rebuilder,10.0.0.1:6032: err  25127 1D62AF0 log ERROR ERROR while rebuilding chunk 8C45CFEBA81476E9BADD4652B2958F7309535FA8D02EC0469D521B4D5736FE7F|C24388F8B04A0500664E26687DBD93D2|08748BB9C9954E6791688AA9C069EEEF16A7315E7662FD1484B6CB97E9761F0B) : Content not found`

maybe add "possible orphan chunk"?

**Comment by kamel-rahim** [comment]
This is fix with the PR #982.
