### ISSUE TITLE
Implement container flush

### ISSUE THREAD

**Issue by GuillaumeDelaporte** [open-io/oio-sds#918]
It could be very interesting to have something like `openio container flush mycontainer` or `openio object delete mycontainer *`

**Comment by gdelafond** [comment]
It could be very dangerous, I think we need to have a confirmation before doing the job. Maybe with a "bypass" to be able to automate it with an env variable, or a --force option ?
```
$ openio container flush mycontainer
X objects will be deleted from "mycontainer", are you sure ? (y/N)
```

With env variable: 
`$ ALLOW_CONTAINER_FLUSH=1 openio container flush mycontainer`

With --force option: 
`$ openio container flush --force mycontainer`

Any thoughts about this ?

**Comment by fvennetier** [comment]
The delete with wildcard is dangerous (you want to `delete a*` but you type `delete *`). When you type `flush` there is no possible confusion. I think asking for a confirmation is excessive.

**Comment by aneutron** [comment]
Can be very useful when a restore operation goes wrong and we need to delete the container.
