### ISSUE TITLE
High latencies on metadata services problems

### ISSUE THREAD

**Issue by racciari** [open-io/oio-sds#943]
When latencies goes high on metadata services, timeout can show up and slow the whole cluster, especially around the meta1:

```
meta2 e=(500) Open/Lock error: Election failed [0B1E][meta1]
```

We have to work around this log to find a way to avoid this problem.

**Comment by jfsmig** [comment]
I reassigned the milestone for this issue, from 3.3 to 4.0. Several factors her for such a decision:
* the redesign of the election FSM is the best answer to that kind of problems, and that redesign has been done in the (current) master branch, as a base for the next 4.0 release
* the current 3.3 is the mandatory check-point on the migration path from 3.2 to 4.0.

Let's produce the 3.3 quickly and move forward to the 4.0 right after.
