### ISSUE TITLE
conscience memory segment consumption

### ISSUE THREAD

**Issue by racciari** [open-io/oio-sds#945]
Depending on the configuration and the platform, it appears that the worker pool management is consuming memory segments ending up for the conscience to fail creating new workers with the log:

```
oio.gridd.srv Cannot start a worker thread : Error creating thread: Resource temporarily unavailable
```

The conscience seems to create way too much memory segments that are listed in `/proc/<pid>/maps` and the maximum is available through cat `/proc/sys/vm/max_map_count`
A workaround of the problem is to set `min_workers` = `max_workers`, so it seems to be linked to the creation/suppression of workers.

**Comment by jfsmig** [comment]
Ok, it seems the worker threads are not joined nor detached. Let's do it, it will help.
