### ISSUE TITLE
Reload configuration on special signal

### ISSUE THREAD

**Issue by fvennetier** [open-io/oio-sds#974]
Since #969 (4.0.0), sqliterepo-based services and oio-proxy do not reload their local configuration automatically, and you have to restart them to do so. We would like to be able to trigger a configuration reload on a special signal, for example  `SIGHUP` (`SIGUSR1` and `SIGUSR2` are already used to control logging level).

**Comment by jfsmig** [comment]
Also does `oio-rdir-server`
